/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  safelist: [
    'flex','hidden','text-primary','border-primary','text-on-surface-variant',
    'border-transparent','opacity-0','opacity-100','translate-y-0',
    { pattern: /^(text|bg|border)-(primary|error|on-surface)/ },
  ],
  theme: {
    extend: {
      colors: {
        "primary":                 "#CC0000",
        "on-primary":              "#ffffff",
        "primary-container":       "#ffdad6",
        "on-primary-container":    "#410002",
        "secondary":               "#5f5e5e",
        "on-secondary":            "#ffffff",
        "secondary-container":     "#e2dfde",
        "on-secondary-container":  "#636262",
        "surface":                 "#fbf9f9",
        "on-surface":              "#1b1c1c",
        "surface-variant":         "#e3e2e2",
        "on-surface-variant":      "#5d3f3c",
        "background":              "#fbf9f9",
        "on-background":           "#1b1c1c",
        "error":                   "#CC0000",
        "on-error":                "#ffffff",
        "error-container":         "#ffdad6",
        "on-error-container":      "#93000a",
        "outline":                 "#926f6b",
        "outline-variant":         "#e7bdb8",
        "surface-container":       "#efeded",
        "surface-container-low":   "#f5f3f3",
        "surface-container-high":  "#e9e8e7",
        "surface-container-highest":"#e3e2e2",
        "surface-container-lowest":"#ffffff",
        "surface-bright":          "#fbf9f9",
        "surface-dim":             "#dbdad9",
        "inverse-surface":         "#303031",
        "inverse-on-surface":      "#f2f0f0",
        "inverse-primary":         "#ffb4ab",
        "tertiary":                "#5b5b58",
        "on-tertiary":             "#ffffff",
        "tertiary-container":      "#747470",
        "on-tertiary-container":   "#fdfbf6",
      },
      spacing: {
        "unit":           "4px",
        "section-gap":    "120px",
        "margin-mobile":  "20px",
        "margin-desktop": "80px",
        "gutter":         "24px",
      },
      maxWidth: { "container-max": "1280px" },
      fontFamily: {
        "label-sm":   ["Hanken Grotesk","sans-serif"],
        "label-md":   ["Hanken Grotesk","sans-serif"],
        "label-lg":   ["Hanken Grotesk","sans-serif"],
        "body-md":    ["Hanken Grotesk","sans-serif"],
        "body-lg":    ["Hanken Grotesk","sans-serif"],
        "headline-sm":["Libre Caslon Text","serif"],
        "headline-md":["Libre Caslon Text","serif"],
        "headline-lg":["Libre Caslon Text","serif"],
        "display-lg": ["Libre Caslon Text","serif"],
      },
      fontSize: {
        "label-sm": ["12px",{"lineHeight":"1.2","letterSpacing":"0.03em","fontWeight":"500"}],
        "label-md": ["12px",{"lineHeight":"1.2","letterSpacing":"0.05em","fontWeight":"500"}],
        "label-lg": ["14px",{"lineHeight":"1.2","letterSpacing":"0.05em","fontWeight":"600"}],
        "body-md":  ["16px",{"lineHeight":"1.6","fontWeight":"400"}],
        "body-lg":  ["18px",{"lineHeight":"1.6","fontWeight":"400"}],
        "headline-sm":["24px",{"lineHeight":"1.4","fontWeight":"400"}],
        "headline-md":["28px",{"lineHeight":"1.3","fontWeight":"600"}],
        "headline-lg":["40px",{"lineHeight":"1.2","fontWeight":"700"}],
        "display-lg": ["64px",{"lineHeight":"1.1","letterSpacing":"-0.02em","fontWeight":"700"}],
      },
      borderRadius: {
        DEFAULT:"0.25rem", lg:"0.5rem", xl:"0.75rem", full:"9999px",
      },
    },
  },
  plugins: [],
}
